### ISSUE TITLE
Vault provider has problems with corrupted S3 remote state.  Recurring, but infrequent.

### ISSUE THREAD

**Issue by queglay** [hashicorp/terraform-provider-vault#1012]
### Terraform Version
terraform 0.13.5

### Affected Resource(s)
- vault and remote state

### Panic Output
```
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /tmp/plugin222707894: connect: connection refused"
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /tmp/plugin222707894: connect: connection refused"
```

### Expected Behavior
I should be able to configure vault without error

### Actual Behavior
I see RPC errors.  This has occured multiple times but it is infrequent (perhaps a month apart).  The only way to fix it last time was to delete my entire remote state S3 bucket.
This time I was hoping to just delete the folder related to this problem but then I get:
```
Error refreshing state: state data in S3 does not have the expected content.

This may be caused by unusually long delays in S3 processing a previous state
update.  Please wait for a minute or two and try again. If this problem
persists, and neither S3 nor DynamoDB are experiencing an outage, you may need
to manually verify the remote state and update the Digest value stored in the
DynamoDB table to the following value: 
```

### Steps to Reproduce
1. `terraform apply`

**Comment by queglay** [comment]
Before I was able to work around this by emptying my vault S3 backend, and erasing any entries in dynamo DB that might be connected.

I think I'm in an automated scenario where I can reproduce this always now though.  Today I see repeatedly after trying to configure vault with terraform:

```
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
```

I currently cannot use terraform to configure vault reliably.

**Comment by queglay** [comment]
I decided to isolate as many different components in my vault config into seperate modules as would be reasonable.  So far I can tell all crashes do share pki queries from terraform.

```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
- Installed hashicorp/aws v3.35.0 (signed by HashiCorp)
vault_mount.ssh_signer: Refreshing state... [id=ssh-client-signer]
vault_mount.ssh_host_signer: Refreshing state... [id=ssh-host-signer]
vault_ssh_secret_backend_ca.ssh_host_signer_ca: Refreshing state... [id=ssh-host-signer]
vault_ssh_secret_backend_role.host_role: Refreshing state... [id=ssh-host-signer/roles/hostrole]
vault_ssh_secret_backend_ca.ssh_signer_ca: Refreshing state... [id=ssh-client-signer]
vault_ssh_secret_backend_role.ssh_role: Refreshing state... [id=ssh-client-signer/roles/ssh-role]
vault_mount.pki: Refreshing state... [id=pki]
vault_mount.pki_int: Refreshing state... [id=pki_int]
vault_pki_secret_backend_crl_config.pki_int_crl_config: Refreshing state... [id=pki_int/config/crl]
vault_pki_secret_backend_role.firehawkvfx-dot-com: Refreshing state... [id=pki_int/roles/firehawkvfx-dot-com]
vault_pki_secret_backend_intermediate_cert_request.intermediate: Refreshing state... [id=pki_int/intermediate/generate/internal]
vault_pki_secret_backend_crl_config.pki_crl_config: Refreshing state... [id=pki/config/crl]
vault_pki_secret_backend_root_cert.root: Refreshing state... [id=pki/root/generate/internal]

Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Canceled desc = context canceled



Error: rpc error: code = Unavailable desc = transport is closing



Error: rpc error: code = Unavailable desc = transport is closing




!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
panic: runtime error: invalid memory address or nil pointer dereference
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1011cf5]
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: 
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: goroutine 47 [running]:
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: github.com/hashicorp/terraform-provider-vault/vault.pkiSecretBackendCrlConfigRead(0xc0006097a0, 0x131ffa0, 0xc00030e620, 0xc0006097a0, 0x0)
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_pki_secret_backend_crl_config.go:84 +0x305
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000120480, 0xc00076d360, 0x131ffa0, 0xc00030e620, 0xc00000e830, 0x0, 0x0)
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x119
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000e160, 0x160d8e0, 0xc0008fe240, 0xc000596cc0, 0xc00000e160, 0x0, 0xc000448b78)
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x12f9580, 0xc00000e160, 0x160d8e0, 0xc0008fe240, 0xc000596c60, 0x0, 0x160d8e0, 0xc0008fe240, 0xc0003f0380, 0x6a)
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x217
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001800, 0x161a1e0, 0xc0000acc00, 0xc000187100, 0xc0004b7b30, 0x1f07650, 0x0, 0x0, 0x0)
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:1024 +0x501
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc000001800, 0x161a1e0, 0xc0000acc00, 0xc000187100, 0x0)
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:1313 +0xd3d
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000a0470, 0xc000001800, 0x161a1e0, 0xc0000acc00, 0xc000187100)
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:722 +0xa1
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-02T12:48:08.373Z [DEBUG] plugin.terraform-provider-vault_v2.19.0_x4:    /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:720 +0xa1
2021-04-02T12:48:08.375Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/vault/2.19.0/linux_amd64/terraform-provider-vault_v2.19.0_x4 pid=15453 error="exit status 2"
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Canceled desc = context canceled
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Canceled desc = context canceled
2021/04/02 12:48:08 [TRACE] [walkRefresh] Exiting eval tree: vault_pki_secret_backend_crl_config.pki_crl_config
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_crl_config": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_crl_config": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_crl_config": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_crl_config (expand)": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_crl_config (expand)": visit complete
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/04/02 12:48:08 [TRACE] [walkRefresh] Exiting eval tree: vault_pki_secret_backend_crl_config.pki_int_crl_config
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_int_crl_config": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_int_crl_config": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_int_crl_config": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_int_crl_config (expand)": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_crl_config.pki_int_crl_config (expand)": visit complete
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/04/02 12:48:08 [TRACE] [walkRefresh] Exiting eval tree: vault_pki_secret_backend_role.firehawkvfx-dot-com
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_role.firehawkvfx-dot-com": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_role.firehawkvfx-dot-com": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_role.firehawkvfx-dot-com": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_role.firehawkvfx-dot-com (expand)": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_role.firehawkvfx-dot-com (expand)": visit complete
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/04/02 12:48:08 [TRACE] [walkRefresh] Exiting eval tree: vault_pki_secret_backend_intermediate_cert_request.intermediate
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_intermediate_cert_request.intermediate": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_intermediate_cert_request.intermediate": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_intermediate_cert_request.intermediate": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_intermediate_cert_request.intermediate (expand)": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_intermediate_cert_request.intermediate (expand)": visit complete
2021/04/02 12:48:08 [TRACE] dag/walk: upstream of "vault_pki_secret_backend_root_sign_intermediate.root (expand)" errored, so skipping
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2021/04/02 12:48:08 [ERROR] eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2021/04/02 12:48:08 [TRACE] [walkRefresh] Exiting eval tree: vault_pki_secret_backend_root_cert.root
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_root_cert.root": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_root_cert.root": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_root_cert.root": visit complete
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_root_cert.root (expand)": dynamic subgraph encountered errors
2021/04/02 12:48:08 [TRACE] vertex "vault_pki_secret_backend_root_cert.root (expand)": visit complete
2021/04/02 12:48:08 [TRACE] dag/walk: upstream of "vault_pki_secret_backend_intermediate_set_signed.intermediate (expand)" errored, so skipping
2021/04/02 12:48:08 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/vault\"] (close)" errored, so skipping
2021/04/02 12:48:08 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021-04-02T12:48:08.430Z [DEBUG] plugin: plugin exited

ERRO[0576] Module /home/ec2-user/environment/firehawk/vault-init/firehawk-main/modules/vault-userpass has finished with an error: Hit multiple errors:
Hit multiple errors:
exit status 1  prefix=[/home/ec2-user/environment/firehawk/vault-init/firehawk-main/modules/vault-userpass] 
module.update-values-resourcetier["network/private_domain"].null_resource.init_secret: Refreshing state... [id=8398061877926047839]
module.update-values-resourcetier["network/openvpn_user_pw"].null_resource.init_secret: Refreshing state... [id=3191994908491381367]
module.update-values-resourcetier["network/openvpn_admin_pw"].null_resource.init_secret: Refreshing state... [id=2945527704074155937]
module.update-values-resourcetier["system/deployuser_uid"].null_resource.init_secret: Refreshing state... [id=7849396579334198173]
module.update-values-resourcetier["aws/bucket_extension"].null_resource.init_secret: Refreshing state... [id=6284593994078831726]
module.update-values-resourcetier["ansible/selected_ansible_version"].null_resource.init_secret: Refreshing state... [id=3774059905396172799]
module.update-values-resourcetier["deadline/deadline_version"].null_resource.init_secret: Refreshing state... [id=8514925224181441069]
module.update-values-resourcetier["system/deadlineuser_uid"].null_resource.init_secret: Refreshing state... [id=919011506141590716]
module.update-values-resourcetier["system/syscontrol_gid"].null_resource.init_secret: Refreshing state... [id=1443506672902916695]
```

**Comment by benashz** [comment]
This issue appears to be related to Terraform specifically. We suggest upgrading to the latest version of Terraform to see if that resolves the issue. If not it may be good to post his issue to the [terraform](https://github.com/hashicorp/terraform) project directly.
