### ISSUE TITLE
make generate is broken

### ISSUE THREAD

**Issue by greut** [hashicorp/terraform-provider-vault#1130]
Since e97b8882f4f25c99ad46d1fe1876782389e20d2d according to `git bisect`, `make generate` doesn't work anymore.

```console
$ make generate
result=go run cmd/generate/main.go -openapi-doc=testdata/openapi.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x80c3fa]
goroutine 1 [running]:
github.com/hashicorp/terraform-provider-vault/codegen.parseParameters(0x0, 0xc00010e360, 0x10, 0x10, 0x7fa29ca9d3c8)
        /home/yoan/soft/terraform-provider-vault/codegen/templates.go:126 +0xda
github.com/hashicorp/terraform-provider-vault/codegen.(*templateHandler).toTemplatable(0xc0000207a0, 0x90fd20, 0x16, 0x0, 0xc00010e360, 0xc000596000, 0xc0006fc2a0, 0xc0006fc298)
        /home/yoan/soft/terraform-provider-vault/codegen/templates.go:94 +0x4d
github.com/hashicorp/terraform-provider-vault/codegen.(*templateHandler).Write(0xc0000207a0, 0x991d40, 0xc000807200, 0x2, 0x90fd20, 0x16, 0x0, 0xc00010e360, 0x909356, 0x9)
        /home/yoan/soft/terraform-provider-vault/codegen/templates.go:81 +0x13a
github.com/hashicorp/terraform-provider-vault/codegen.(*fileCreator).writeFile(0xc000704390, 0xc000814180, 0x53, 0x2, 0x90fd20, 0x16, 0x0, 0xc00010e360, 0x0, 0x0)
        /home/yoan/soft/terraform-provider-vault/codegen/generate.go:109 +0x10a
github.com/hashicorp/terraform-provider-vault/codegen.(*fileCreator).GenerateCode(0xc000704390, 0x90fd20, 0x16, 0x0, 0xc00010e360, 0x2, 0x0)
        /home/yoan/soft/terraform-provider-vault/codegen/generate.go:81 +0xd9
github.com/hashicorp/terraform-provider-vault/codegen.Run(0x99e968, 0xc000138000, 0xc0001cfce0, 0x0, 0x0)
        /home/yoan/soft/terraform-provider-vault/codegen/generate.go:38 +0x1de
main.main()
        /home/yoan/soft/terraform-provider-vault/cmd/generate/main.go:37 +0x24f
exit status 2
make: *** [GNUmakefile:25: generate] Error 1
```

**Comment by BrandonIngalls** [comment]
Looks like `testdata/openapi.json` is missing documentation for the `transform` secrets engine.

Adding this made the panic go away.
```
    "/transform/encode/{role_name}": {
      "description": "TBD",
      "get": {},
      "post": {},
      "delete": {}
    },
    "/transform/decode/{role_name}": {
      "description": "TBD",
      "get": {},
      "post": {},
      "delete": {}
    },
    "/transform/role/{name}": {
      "description": "TBD",
      "get": {},
      "post": {},
      "delete": {}
    },
    "/transform/alphabet/{name}": {
      "description": "TBD",
      "get": {},
      "post": {},
      "delete": {}
    },
    "/transform/template/{name}": {
      "description": "TBD",
      "get": {},
      "post": {},
      "delete": {}
    },
    "/transform/transformation/{name}": {
      "description": "TBD",
      "get": {},
      "post": {},
      "delete": {}
    },
```

It would probably be nice to add some error handling to `cmd/generate` to make debugging this issue easier in the future.

According to [/codegen/README.md](https://github.com/hashicorp/terraform-provider-vault/blob/f3056c10a520674edb60e3f0f0ede9b30fc13a2b/codegen/README.md#:~:text=to%20generate%20code.-,If%20it%20doesn%27t%3A,-Make%20a%20new) someone needs to checkout the vault enterprise version of the repo and run a script to generate a new `openapi.json` file.

**Comment by benashz** [comment]
Thanks for reporting this. We are currently re-evaluating our code generation strategy, so this feature is currently disabled.
