### ISSUE TITLE
Error making API request on updating IdentityGroup

### ISSUE THREAD

**Issue by Keramblock** [hashicorp/terraform-provider-vault#1144]
### Terraform Version
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/google v3.79.0
+ provider registry.terraform.io/hashicorp/google-beta v3.79.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v2.1.1
+ provider registry.terraform.io/hashicorp/vault v2.22.1

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_identity_group
### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "vault_identity_group" "vault-developer" {
  name     = "vault-dev@example.com"
  type     = "external"
  policies = [vault_policy.developer.name]

  metadata = {
    responsibility="Vault Developers Google Group permissions mapping"
  }
}
```

### Expected Behavior
It succesfully changed in place metadata.responsibility field or recreated it

### Actual Behavior
Plan:
```hcl
  # module.my-infra.vault_identity_group.vault-developer will be updated in-place
  ~ resource "vault_identity_group" "vault-developer" {
        id                         = "<id-here>"
      ~ metadata                   = {
          ~ "responsibility" = "Vault Developers Google Group permissions mappnig" -> "Vault Developers Google Group permissions mapping"
        }
        name                       = "vault-dev@example.com"
        # (6 unchanged attributes hidden)
    }
```
Apply:
```hcl
module.my-infra.vault_identity_group.vault-developer: Modifying... [id=<id-here>]
╷
│ Error: error updating IdentityGroup "<id-here>": Error making API request.
│
│ URL: PUT https://vault.infra.example.com/v1/identity/group/id/<id-here>
│ Code: 400. Errors:
│
│ * member entities can't be set manually for external groups
│
│   with module.my-infra.vault_identity_group.vault-developer,
│   on ../../modules/my-infra/vault_auth.tf line 50, in resource "vault_identity_group" "vault-developer":
│   50: resource "vault_identity_group" "vault-developer" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Change metadata.responsibility field of vault_identity_group resource
2. terraform apply
3. yes

### References
Did not found any

**Comment by Keramblock** [comment]
On taint:
Plan:
```hcl
  # module.my-infra.vault_identity_group.vault-developer is tainted, so must be replaced
-/+ resource "vault_identity_group" "vault-developer" {
      ~ id                         = "<id-here>" -> (known after apply)
      - member_entity_ids          = [
          - "<id-here>",
        ] -> null
      - member_group_ids           = [] -> null
      ~ metadata                   = {
          ~ "responsibility" = "Vault Developers Google Group permissions mappnig" -> "Vault Developers Google Group permissions mapping"
        }
        name                       = "vault-dev@example.com"
        # (4 unchanged attributes hidden)
    }
```
Apply:
```hcl
╷
│ Error: Plugin did not respond
│
│   with module.my-infra.vault_identity_group_alias.vault-developer,
│   on ../../modules/my-infra/vault_auth.tf line 60, in resource "vault_identity_group_alias" "vault-developer":
│   60: resource "vault_identity_group_alias" "vault-developer" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
```
Error below:
```hcl
Stack trace from the terraform-provider-vault_v2.22.1_x4 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1af09c7]

goroutine 72 [running]:
github.com/hashicorp/terraform-provider-vault/vault.identityGroupAliasUpdate(0xc0000ccf50, 0x1d8d320, 0xc00099e280, 0x24, 0x2611140)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vault/vault/resource_identity_group_alias.go:85 +0x307
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000376d80, 0xc00098e140, 0xc0009361a0, 0x1d8d320, 0xc00099e280, 0x1c60501, 0xc0009b38d0, 0xc000982f30)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/resource.go:316 +0x273
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000228680, 0xc0009b3a38, 0xc00098e140, 0xc0009361a0, 0xc00098d5e8, 0xc0007ce028, 0x1c62780)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000ec18, 0x1fb4850, 0xc000982000, 0xc0000cc070, 0xc00000ec18, 0xc000982000, 0xc0007a2ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1d5b1a0, 0xc00000ec18, 0x1fb4850, 0xc000982000, 0xc0007e6060, 0x0, 0x1fb4850, 0xc000982000, 0xc000978800, 0x1e1)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.9.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00038e1a0, 0x1fbf738, 0xc000001e00, 0xc00083e000, 0xc000783500, 0x25d0640, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00038e1a0, 0x1fbf738, 0xc000001e00, 0xc00083e000, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xccf
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003a230, 0xc00038e1a0, 0x1fbf738, 0xc000001e00, 0xc00083e000)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5

Error: The terraform-provider-vault_v2.22.1_x4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by Keramblock** [comment]
So probably there is two errors

**Comment by Keramblock** [comment]
Hi, @tvoran seems that bot failed to triage this issue: https://github.com/hashicorp/terraform-provider-vault/actions/runs/1120154961

Could you help with it please?

**Comment by thor** [comment]
I believe this issue (as described in the description, not the additional comments) is due to e9afb6f80dd2e0c677096caf6c46b4f38043f9d8 from #1061.

After the change `member_entity_ids` is passed along by default as an empty list, if I'm correct in that `.List()` indeed results in an empty slice. This is in contrast to what it should be for `external` groups, which is to keep it `null` or not even specified.

A possible patch would be to avoid setting either of the values related to `internal` groups unless, indeed, it is an `internal` group where those values apply.

**Comment by benashz** [comment]
This issue should be fixed in the most recent release of the provider. Please let us know if you are still experiencing this issue.

Thanks,

Ben
