### ISSUE TITLE
Provider Crashing on v3.2.0

### ISSUE THREAD

**Issue by AnthonyHerman** [hashicorp/terraform-provider-vault#1309]
Getting the below panic in our pipeline after updating to provider v3.2.0 w/ terraform v1.0.0. Running in Github actions workflow. Let me know what other logs could be helpful, thanks. I pinned to v3.1.1 for the time being.

Looks like it was probably introduced in #1246

### Terraform Version
1.0.0

### Panic Output
```
Stack trace from the terraform-provider-vault_v3.2.0_x4 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 71437 [running]:
github.com/hashicorp/terraform-provider-vault/vault.rabbitMQSecretBackendRoleRead(0xc000c8e000, {0x10d1280, 0xc000b01d60})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-vault/vault/resource_rabbitmq_secret_backend_role.go:175 +0x648
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x10dec2d, {0x134f2e8, 0xc0008165c0}, 0x24, {0x10d1280, 0xc000b01d60})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001a21c0, {0x134f2e8, 0xc0008165c0}, 0xc0009a0d00, {0x10d1280, 0xc000b01d60})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c3a8, {0x134f2e8, 0xc0008165c0}, 0xc000816640)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.0/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc00012e880, {0x134f390, 0xc0009bdb60}, 0xc000ab8360)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x109ac20, 0xc00012e880}, {0x134f390, 0xc0009bdb60}, 0xc000ab8300, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000332c40, {0x13654c0, 0xc00024e480}, 0xc000945440, 0xc0002179e0, 0x1b28eb0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000332c40, {0x13654c0, 0xc00024e480}, 0xc000945440, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:923 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.41.0/server.go:921 +0x294

Error: The terraform-provider-vault_v3.2.0_x4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce
1. `terraform apply`

**Comment by AnthonyHerman** [comment]
This is how we've had our `vault_rabbitmq_secret_backend_role` resources looking up to this point:

```tf
resource "vault_rabbitmq_secret_backend_role" "rabbitmq_dev_xx" {
  backend = vault_rabbitmq_secret_backend.rabbitmq-plugins-dev.path
  name    = "rabbitmq_dev_xx"
  vhost {
    host      = "/"
    write     = ".*"
    read      = ".*"
    configure = ".*"
  }
}
```

**Comment by benashz** [comment]
Hi @AnthonyHerman , we just released [v3.2.1](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v3.2.1) to address your issue. Please let us know if you still need any assistance in this regard.

Thanks,

Ben

**Comment by AnthonyHerman** [comment]
@benashz looks good, thanks!

**Comment by benashz** [comment]
Awesome! Thanks for the confirmation @AnthonyHerman !
