### ISSUE TITLE
Panic from vault_pki_secret_backend_role

### ISSUE THREAD

**Issue by evilmog** [hashicorp/terraform-provider-vault#1679]
panic: unknown resource type vault_pki_secret_backend

goroutine 603 [running]:
github.com/hashicorp/terraform/plugin.(*GRPCProvider).getResourceSchema(0xe111a5d?, {0xc001e10cf0, 0x18})
github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:92 +0x10b
github.com/hashicorp/terraform/plugin.(*GRPCProvider).ReadResource(0xc000a17650, {{0xc001e10cf0, 0x18}, {{{0xf0b0bd8, 0xc000a39f80}}, {0xcb81b00, 0xc00055f7d0}}, {0x152ef6d8, 0x0, 0x0}})
github.com/hashicorp/terraform@v0.12.31/plugin/grpc_provider.go:321 +0x74
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper.(*ProviderWrapper).Refresh(0xc000a162a0, 0xc001e2c320, 0xc001e2c2d0)
github.com/GoogleCloudPlatform/terraformer/terraformutils/providerwrapper/provider.go:171 +0x3a9
github.com/GoogleCloudPlatform/terraformer/terraformutils.(*Resource).Refresh(0xc001fdc990, 0x26?)
github.com/GoogleCloudPlatform/terraformer/terraformutils/resource.go:130 +0x4e
github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResourceWorker(0x0?, 0x0?, 0x0?)
github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:153 +0xad
created by github.com/GoogleCloudPlatform/terraformer/terraformutils.RefreshResources
github.com/GoogleCloudPlatform/terraformer/terraformutils/utils.go:80 +0xe7

terraform 1.3.5

Provider block below

terraform {
required_providers {
vault = {
version = "~> 3.11.0"
}
}
}

Vault version 1.12.1

**Comment by benashz** [comment]
@evilmog The panic does not appear to come from the vault provider code. Would you be able to provide any additional information related to this issue?

**Comment by evilmog** [comment]
terraformer throws the error whenever we try to import an existing
configuration from hashicorp vault, its weird

**Comment by evilmog** [comment]
specifically the ssh secrets backend
