### ISSUE TITLE
3.13.0: panic: IsEnterpriseSupported

### ISSUE THREAD

**Issue by seanamos** [hashicorp/terraform-provider-vault#1784]
After upgrading to v3.13.0, we are unable to run our Vault Terraform which has a `vault_raft_autopilot` resource. This is a non-enterprise installation.

We have `skip_get_vault_version = true` set on the provider.

### Terraform Version
v1.3.2

### Affected Resource(s)
- vault_raft_autopilot

### Panic Output
```
Stack trace from the terraform-provider-vault_v3.13.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100cafa10]

goroutine 146 [running]:
github.com/hashicorp/go-version.(*Version).Metadata(...)
        github.com/hashicorp/go-version@v1.6.0/version.go:322
github.com/hashicorp/terraform-provider-vault/internal/provider.(*ProviderMeta).IsEnterpriseSupported(0x0?)
        github.com/hashicorp/terraform-provider-vault/internal/provider/meta.go:116 +0x20
github.com/hashicorp/terraform-provider-vault/internal/provider.IsEnterpriseSupported({0x1013d2880?, 0x14000ac49c0?})
        github.com/hashicorp/terraform-provider-vault/internal/provider/meta.go:367 +0x50
github.com/hashicorp/terraform-provider-vault/vault.createOrUpdateAutopilotConfigResource(0x14000522f68?, {0x1013d2880, 0x14000ac49c0})
        github.com/hashicorp/terraform-provider-vault/vault/resource_raft_autopilot.go:106 +0x1a4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x101501b70?, {0x101501b70?, 0x14000394750?}, 0xd?, {0x1013d2880?, 0x14000ac49c0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:695 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140001447e0, {0x101501b70, 0x14000394750}, 0x140003fc5b0, 0x140003d2680, {0x1013d2880, 0x14000ac49c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400078e690, {0x101501ac8?, 0x14000b8f100?}, 0x14000d18050)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400097e320, {0x101501b70?, 0x14000ab6db0?}, 0x14000902d20)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x384
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x101499ac0?, 0x1400097e320}, {0x101501b70, 0x14000ab6db0}, 0x14000902cb0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140006be3c0, {0x1015068e0, 0x14000248b60}, 0x140005beb40, 0x14000595470, 0x101dbeec0, 0x0)
        google.golang.org/grpc@v1.50.0/server.go:1318 +0x9c4
google.golang.org/grpc.(*Server).handleStream(0x140006be3c0, {0x1015068e0, 0x14000248b60}, 0x140005beb40, 0x0)
        google.golang.org/grpc@v1.50.0/server.go:1659 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.0/server.go:955 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.0/server.go:953 +0x290

Error: The terraform-provider-vault_v3.13.0_x5 plugin crashed!
```

### References
This seems related to: https://github.com/hashicorp/terraform-provider-vault/pull/1721

### Workaround
Downgrade

**Comment by vinay-gopalan** [comment]
Thanks for reporting the issue! This should be fixed in #1787 and will be released in the patch version v3.13.1 of the TFVP. Please let us know if you still see any issues!
