### ISSUE TITLE
Error: The terraform-provider-vault_v3.16.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by hagaimaya** [hashicorp/terraform-provider-vault#1899]
Hi there,

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- vault_database_secret_backend_connection

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Panic Output
panic: interface conversion: interface {} is string, not []interface {}

goroutine 146 [running]:
github.com/hashicorp/terraform-provider-vault/vault.getDBCommonConfig(0x14000c10200?, 0x140005feb40, 0x10405e960, 0x10355e3c0?, 0x0, {0x14000564644, 0xf})
	github.com/hashicorp/terraform-provider-vault/vault/resource_database_secret_backend_connection.go:1709 +0x69c
github.com/hashicorp/terraform-provider-vault/vault.databaseSecretBackendConnectionRead(0x14000c10200, {0x103676ac0?, 0x14000b9c4c0?})
	github.com/hashicorp/terraform-provider-vault/vault/resource_database_secret_backend_connection.go:1696 +0x444
github.com/hashicorp/terraform-provider-vault/vault.databaseSecretBackendConnectionCreateOrUpdate(0x140006c2f68?, {0x103676ac0, 0x14000b9c4c0})
	github.com/hashicorp/terraform-provider-vault/vault/resource_database_secret_backend_connection.go:1554 +0x158
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1037a6130?, {0x1037a6130?, 0x14000d502d0?}, 0xd?, {0x103676ac0?, 0x14000b9c4c0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:695 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400087b880, {0x1037a6130, 0x14000d502d0}, 0x14000c90410, 0x14000c10080, {0x103676ac0, 0x14000b9c4c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/resource.go:837 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140008aa6d8, {0x1037a6088?, 0x140006592c0?}, 0x14000d3d810)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.16.0/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000924f00, {0x1037a6130?, 0x140009ea1e0?}, 0x14000ba2620)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x384
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10373dc80?, 0x14000924f00}, {0x1037a6130, 0x140009ea1e0}, 0x14000ba25b0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400002c3c0, {0x1037aaea0, 0x14000536680}, 0x140009f9200, 0x14000985410, 0x10406b0c0, 0x0)
	google.golang.org/grpc@v1.50.0/server.go:1318 +0x9c4
google.golang.org/grpc.(*Server).handleStream(0x1400002c3c0, {0x1037aaea0, 0x14000536680}, 0x140009f9200, 0x0)
	google.golang.org/grpc@v1.50.0/server.go:1659 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.0/server.go:955 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.0/server.go:953 +0x290

Error: The terraform-provider-vault_v3.16.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by hagaimaya** [comment]
was fixed when changing the 'vault_mount' to 'database'

**Comment by hagaimaya** [comment]
found workaround / fix
