### ISSUE TITLE
Wrote IdentityEntity: panic: runtime error: invalid memory address or nil pointer

### ISSUE THREAD

**Issue by hixichen** [hashicorp/terraform-provider-vault#734]
**terraform --version
Terraform v0.12.24**
```
2020/04/21 04:01:24 [DEBUG] module.dca20.vault_identity_entity.personnel["apxxxxxx@xyz.com"]: applying the planned Create change
2020/04/21 04:01:24 [TRACE] GRPCProvider: ApplyResourceChange
2020-04-21T04:01:24.610Z [DEBUG] plugin.terraform-provider-vault_v2.9.0_x4: 2020/04/21 04:01:24 [DEBUG] Wrote IdentityEntity "apxxxxxx@xyz.com"
2020-04-21T04:01:24.613Z [DEBUG] plugin.terraform-provider-vault_v2.9.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2020-04-21T04:01:24.613Z [DEBUG] plugin.terraform-provider-vault_v2.9.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf2ed90]
2020-04-21T04:01:24.613Z [DEBUG] plugin.terraform-provider-vault_v2.9.0_x4: 
2020-04-21T04:01:24.613Z [DEBUG] plugin.terraform-provider-vault_v2.9.0_x4: goroutine 48 [running]:
2020-04-21T04:01:24.614Z [DEBUG] plugin.terraform-provider-vault_v2.9.0_x4: github.com/terraform-providers/terraform-provider-vault/vault.identityEntityCreate(0xc0002c2e70, 0x1265b40, 0xc0001621c0, 0x2, 0x1da7b40)
2020-04-21T04:01:24.614Z [DEBUG] plugin.terraform-provider-vault_v2.9.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_identity_entity.go:110 +0x2e0
2020-04-21T04:01:24.614Z [DEBUG] plugin.terraform-provider-vault_v2.9.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00057c500, 0xc0007dcb90, 0xc00079d0a0, 0x1265b40, 0xc0001621c0, 0xc0007f0901, 0xc0008405d0, 0xc0007f0a60)
```

**Comment by hixichen** [comment]
code:
```
https://github.com/terraform-providers/terraform-provider-vault/blob/v2.9.0/vault/resource_identity_entity.go#L110
```

**Comment by jeffsanicola** [comment]
I'm running into the same, or very similar, issue on TF 0.13.0, Vault 1.5.0, and Vault Provider 2.12.2.

**Comment by dedamico** [comment]
> I'm running into the same, or very similar, issue on TF 0.13.0, Vault 1.5.0, and Vault Provider 2.12.2.

I have been working with @jeffsanicola via HashiCorp support ticket and wanted to post the recreate steps he provided with the mentioned TF/Vault/Provider versions:

**Steps to reproduce:**

1. Create an AppRole role ID and associated Identity Entity (see below module and root main.tf):
2. Using a fresh Terraform state file, repeat step 1
3. Crash

**Terraform module**:
```
#Get the AppRole auth backend details
data "vault_auth_backend" "approle" {
  path = var.mount_point
}

#Dynamic policies - one will be created for each approle
data "vault_policy_document" "role_id" {
  rule {
    path         = "auth/${data.vault_auth_backend.approle.path}/role/${vault_approle_auth_backend_role.approle.role_name}/role-id"
    capabilities = ["read"]
    description  = "Read role-id for ${vault_approle_auth_backend_role.approle.role_name}"
  }
}

data "vault_policy_document" "secret_id" {
  rule {
    path         = "auth/${data.vault_auth_backend.approle.path}/role/${vault_approle_auth_backend_role.approle.role_name}/secret-id"
    capabilities = [ "update" ]
    description  = "Generate secret-id for ${vault_approle_auth_backend_role.approle.role_name}"
  }
}

resource "vault_policy" "role_id" {
  name     = "approle_${vault_approle_auth_backend_role.approle.role_name}_role_id"
  policy   = data.vault_policy_document.role_id.hcl
}

resource "vault_policy" "secret_id" {
  name     = "approle_${vault_approle_auth_backend_role.approle.role_name}_secret_id"
  policy   = data.vault_policy_document.secret_id.hcl
}

resource "vault_approle_auth_backend_role" "approle" {
  backend                = data.vault_auth_backend.approle.path
  role_name              = var.approle_name
  role_id                = var.role_id
  token_policies         = ["default"]
  secret_id_bound_cidrs  = var.login_cidrs
  secret_id_num_uses     = var.num_uses
  bind_secret_id         = true
  token_ttl              = var.token_ttl
  token_max_ttl          = var.token_max_ttl
  token_explicit_max_ttl = var.token_explicit_max_ttl
  token_period           = var.token_period
  token_bound_cidrs      = var.token_cidrs
  token_num_uses         = var.token_num_uses
  token_type             = var.token_type
}

data "vault_approle_auth_backend_role_id" "approle" {
  depends_on = [vault_approle_auth_backend_role.approle]
  backend    = data.vault_auth_backend.approle.path
  role_name  = var.approle_name
}

resource "vault_identity_entity" "approle" {
  name              = "${data.vault_auth_backend.approle.path}-${var.approle_name}"
  external_policies = true
  metadata          = var.metadata
}

resource "vault_identity_entity_policies" "approle" {
  policies = concat(["default"], var.policies)

  exclusive = false

  entity_id = vault_identity_entity.approle.id
}

resource "vault_identity_entity_alias" "approle" {
  canonical_id   = vault_identity_entity.approle.id
  name           = data.vault_approle_auth_backend_role_id.approle.role_id
  mount_accessor = data.vault_auth_backend.approle.accessor
}
```

**Example usage (main.tf root module):**
```
terraform {
required_version = ">= 0.12"
}

provider "vault" {
version = "2.12.2"
max_retries = 5
}

module "approle-module" {
source = "path_to_module"
approle_name = "approle-Name"
role_id = "demo"
policies = [
"approle-test",
"aws-1234567890-test_role"
]
}
```

**variables used to pass to the module:**
```
variable "approle_name" {
  type        = string
  description = "Name for the AppRole"
}

variable "role_id" {
  type        = string
  description = "Custom role_id, can be any string"
  default     = null
}

variable "policies" {
  type        = list(string)
  description = "List of policy names to apply to the role"
  default     = []
}
```

**Comment by dedamico** [comment]
`panic` which @jeffsanicola saw in his testing - stack trace looks the same as the original post on this issue:

```
2020/08/12 08:39:06 [DEBUG] module.IdamPxm-approle.vault_approle_auth_backend_role.approle: applying the planned Create change
2020/08/12 08:39:06 [TRACE] GRPCProvider: ApplyResourceChange
2020-08-12T08:39:06.799-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 2020/08/12 08:39:06 [DEBUG] Writing AppRole auth backend role "auth/approle/role/PV-IdamPxm-VaultNonprod"
2020-08-12T08:39:06.799-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 2020/08/12 08:39:06 [DEBUG] Wrote IdentityEntity "approle-PV-IdamPxm-VaultNonprod"
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: panic: runtime error: invalid memory address or nil pointer dereference
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1baaa60]
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: goroutine 56 [running]:
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: github.com/terraform-providers/terraform-provider-vault/vault.identityEntityCreate(0xc000232d20, 0x1eece00, 0xc0002320e0, 0x2, 0x2afdee0)
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vault/resource_identity_entity.go:110 +0x2e0
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000042500, 0xc0002561e0, 0xc000797340, 0x1eece00, 0xc0002320e0, 0x1d6a301, 0xc00018a1b8, 0xc00056b800)
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:305 +0x365
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000043400, 0xc0002538e0, 0xc0002561e0, 0xc000797340, 0xc000246988, 0xc00000ea78, 0x1d6c480)
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e1d0, 0x21d69c0, 0xc00056af60, 0xc000199e60, 0xc00000e1d0, 0xc00056af60, 0xc000352a48)
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x882
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1ec6960, 0xc00000e1d0, 0x21d69c0, 0xc00056af60, 0xc000199e00, 0x0, 0x21d69c0, 0xc00056af60, 0xc000254000, 0xf4)
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3189 +0x217
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001c4160, 0x21e3180, 0xc000702f00, 0xc00010e800, 0xc0000964e0, 0x2ac2160, 0x0, 0x0, 0x0)
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:995 +0x460
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: google.golang.org/grpc.(*Server).handleStream(0xc0001c4160, 0x21e3180, 0xc000702f00, 0xc00010e800, 0x0)
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:1275 +0xd3d
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00019e540, 0xc0001c4160, 0x21e3180, 0xc000702f00, 0xc00010e800)
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:710 +0xa1
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-08-12T08:39:06.803-0500 [DEBUG] plugin.terraform-provider-vault_v2.12.2_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-vault/vendor/google.golang.org/grpc/server.go:708 +0xa1
2020/08/12 08:39:06 [DEBUG] module.IdamPxm-approle.vault_approle_auth_backend_role.approle: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2020/08/12 08:39:06 [DEBUG] module.IdamPxm-approle.vault_identity_entity.approle: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
```

**Comment by grobie** [comment]
Reproducible with Terraform v0.13.1 and provider registry.terraform.io/hashicorp/vault v2.13.0.

This appears to happen if an identity entity with the given name already exists in Vault. The provider panics instead of rendering an error for the conflict. Looking up the entity ID for the entity name and deleting in in vault with `vault delete identity/entity/id/$id` resolved the issue.

**Comment by yermulnik** [comment]
It seems like we've just hit the same issue but with `vault_identity_group` resource:
```
[…]
2021/03/23 19:59:27 [DEBUG] vault_identity_group.paws: applying the planned Create change
2021/03/23 19:59:27 [TRACE] GRPCProvider: ApplyResourceChange
2021/03/23 19:59:27 [DEBUG] vault_identity_group.run: applying the planned Create change
2021/03/23 19:59:27 [TRACE] GRPCProvider: ApplyResourceChange
2021-03-23T19:59:27.481+0530 [DEBUG] plugin.terraform-provider-vault_v2.16.0_x4: 2021/03/23 19:59:27 [DEBUG] Wrote IdentityGroup "hcom-paws"
2021-03-23T19:59:27.481+0530 [DEBUG] plugin.terraform-provider-vault_v2.16.0_x4: 2021/03/23 19:59:27 [DEBUG] Wrote IdentityGroup "hcom-run"
2021-03-23T19:59:27.490+0530 [DEBUG] plugin.terraform-provider-vault_v2.16.0_x4: panic: runtime error: invalid memory address or nil pointer dereference
2021-03-23T19:59:27.490+0530 [DEBUG] plugin.terraform-provider-vault_v2.16.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1bc920d]
2021-03-23T19:59:27.490+0530 [DEBUG] plugin.terraform-provider-vault_v2.16.0_x4: 
2021-03-23T19:59:27.490+0530 [DEBUG] plugin.terraform-provider-vault_v2.16.0_x4: goroutine 86 [running]:
[…]
2021/03/23 19:59:27 [DEBUG] vault_identity_group.run: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/03/23 19:59:27 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2021/03/23 19:59:27 [DEBUG] vault_identity_group.paws: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/03/23 19:59:27 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2021/03/23 19:59:27 [TRACE] EvalMaybeTainted: vault_identity_group.run encountered an error during creation, so it is now marked as tainted
2021/03/23 19:59:27 [TRACE] EvalMaybeTainted: vault_identity_group.paws encountered an error during creation, so it is now marked as tainted
[…]
```
Provider versions checked to have this issue: 2.16.0 and 2.19.0
